default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  username: root
  password: password
  host: <%= ENV["DB_HOST"] || "localhost" %>
  database: backend_development

test:
  <<: *default
  username: root
  password: password
  host: <%= ENV["DB_HOST"] || "localhost" %>
  database: backend_test

production:
  url: <%= ENV["DATABASE_URL"] %>